// Generated by CoffeeScript 1.9.2
(function() {
  var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Game.Main = (function() {
    function Main(element_id) {
      this.create = bind(this.create, this);
      this.assetsLoaded = bind(this.assetsLoaded, this);
      this.loadAssets = bind(this.loadAssets, this);
      this.element = document.getElementById(element_id);
      console.log(this.element);
      this.stage = new PIXI.Stage(0x66FF99);
      this.renderer = PIXI.autoDetectRenderer(this.element.width, this.element.height, {
        view: this.element
      });
      this.loadAssets();
    }

    Main.prototype.loadAssets = function() {
      var assetsToLoad, loader;
      assetsToLoad = ["images/0_desert@2x.png"];
      loader = new PIXI.AssetLoader(assetsToLoad);
      loader.onComplete = this.assetsLoaded;
      return loader.load();
    };

    Main.prototype.assetsLoaded = function() {
      this.create();
      return requestAnimFrame(this.update.bind(this));
    };

    Main.prototype.update = function() {
      this.renderer.render(this.stage);
      return requestAnimFrame(this.update.bind(this));
    };

    Main.prototype.create = function() {
      return console.log('create');
    };

    return Main;

  })();

}).call(this);
